#include <../include/tests.hpp>
#include <format>
#include <ostream>
#include <sstream>
#include <string>

using namespace std;

string generate_asm(string &contents) {
  stringstream as;

  as << "// Auto-generated by riscv-ctg-srtg" << endl << endl;

  as << ".text" << endl;
  as << ".globl _start" << endl;

  as << "_start:" << endl;
  as << "  call reset_regs" << endl;

  as << endl;

  as << "reset_regs:" << endl;
  // Reset registers
  for (int i = 0; i < 32; i++) {
    as << format("  li x{:}, 0x0", i) << endl;
  }

  as << endl;

  as << contents << endl;

  // Fail and pass funcs
  as << "call pass" << endl;

  as << "fail:" << endl;
  as << "  la t0, pointer" << endl;
  as << "  lh gp, 0(t0)" << endl;
  as << "  li a7, 93" << endl;
  as << "  addi a0, gp, 0" << endl;
  as << "  ecall" << endl << endl;

  as << "pass:" << endl;
  as << "  li a7, 93" << endl;
  as << "  li a0, 0" << endl;
  as << "  ecall" << endl << endl << endl;

  // Generate .data section
  as << ".data" << endl;
  as << ".globl pointer" << endl;
  as << "pointer:" << endl;
  as << "  .short 0" << endl;

  return as.str();
}
