// Copyright (c) 2026 Spalishe. All Rights Reserved.

#include <../include/argparser.h>
#include <../include/tests.hpp>
#include <format>
#include <fstream>
#include <sstream>
#include <string>

using namespace std;

#include <regex>

string execute_line(string &name, vector<string> &args, int index) {
  if (name == "TEST_RR_OP") {
    return TEST_RR_OP(args, index);
  } else if (name == "TEST_IMM_OP") {
    return TEST_IMM_OP(args, index);
  } else if (name == "TEST_CASE") {
    return TEST_CASE(args, index);
  }
  return "";
}

bool parse_line(const string &line, string &name, vector<string> &args) {
  regex r(R"((\w+)\((.*)\))");
  smatch m;

  if (!regex_match(line, m, r))
    return false;

  name = m[1];

  string arg_str = m[2];
  args.clear();

  stringstream ss(arg_str);
  string item;

  while (getline(ss, item, ',')) {
    args.push_back(item);
  }

  return true;
}

int main(int argc, char *argv[]) {
  Argparser::Argparser parser(argc, argv);
  parser.setProgramName("RISC-V CTG Self-Running Tests Generator");
  parser.addArgument("--input", "File to test, generated by riscv-ctg", true,
                     false, Argparser::ArgumentType::str);
  parser.addArgument("--output", "Output file name", true, false,
                     Argparser::ArgumentType::str);

  parser.parse();

  int test_index = 0;
  int c = 0;

  string istr;
  fstream input(parser.getString(0));
  if (!input.is_open()) {
    input.close();
    cout << format("[SRTG] No input file '{0}' found!", parser.getString(0))
         << endl;
    return 0;
  }

  stringstream as;

  while (getline(input, istr)) {
    if (istr.rfind("TEST_", 0) == 0) {
      // We found our test func
      string name;
      vector<string> args;
      if (parse_line(istr, name, args)) {
        string s = execute_line(name, args, test_index);
        if (s == "")
          continue;
        as << s << endl;
        test_index++;
        c++;
      }
    }
  }

  input.close();

  if (c == 0) {
    cout << "[SRTG] Found 0 tests, no purpose on creating file, exiting..."
         << endl;
    return 0;
  }

  fstream out_file(parser.getString(1), ios::out);
  string tests_str = as.str();
  out_file << generate_asm(tests_str) << endl;

  out_file.close();

  cout << format("[SRTG] Wrote {:} tests", c) << endl;

  cout << "[SRTG] Compile with:" << endl;
  string new_out_p = parser.getString(1);
  auto pos = new_out_p.rfind('.');
  if (pos != std::string::npos)
    new_out_p.erase(pos);
  new_out_p = format("{:}{:}", new_out_p, ".o");
  cout << format("       riscvXX-elf-gcc -march=rvXXima -mabi=lpXX -nostdlib "
                 "-Ttext=0x80000000 -static {:} -o {:}",
                 parser.getString(1), new_out_p)
       << endl;

  return 0;
}
